// Code generated by MockGen. DO NOT EDIT.
// Source: hermeskv (interfaces: StoreIface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStoreIface is a mock of StoreIface interface.
type MockStoreIface struct {
	ctrl     *gomock.Controller
	recorder *MockStoreIfaceMockRecorder
}

// MockStoreIfaceMockRecorder is the mock recorder for MockStoreIface.
type MockStoreIfaceMockRecorder struct {
	mock *MockStoreIface
}

// NewMockStoreIface creates a new mock instance.
func NewMockStoreIface(ctrl *gomock.Controller) *MockStoreIface {
	mock := &MockStoreIface{ctrl: ctrl}
	mock.recorder = &MockStoreIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreIface) EXPECT() *MockStoreIfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStoreIface) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStoreIfaceMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStoreIface)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockStoreIface) Get(arg0 string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStoreIfaceMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStoreIface)(nil).Get), arg0)
}

// Set mocks base method.
func (m *MockStoreIface) Set(arg0 string, arg1 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockStoreIfaceMockRecorder) Set(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockStoreIface)(nil).Set), arg0, arg1)
}
